# Generated by Django 4.1 on 2023-03-22 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='all_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='registration',
            fields=[
                ('email', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=50)),
                ('phone', models.IntegerField(default='', unique=True)),
                ('con_password', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='student_details_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('class_student', models.CharField(default='', max_length=50)),
                ('maths', models.IntegerField(default='')),
                ('hindi', models.IntegerField(default='')),
                ('english', models.IntegerField(default='')),
                ('science', models.IntegerField(default='')),
                ('social_studies', models.IntegerField(default='')),
                ('roll_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reglog.all_details')),
            ],
        ),
        migrations.CreateModel(
            name='student_details_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('class_student', models.CharField(default='', max_length=50)),
                ('maths', models.IntegerField(default='')),
                ('hindi', models.IntegerField(default='')),
                ('english', models.IntegerField(default='')),
                ('enviromental_science', models.IntegerField(default='')),
                ('roll_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reglog.all_details')),
            ],
        ),
        migrations.AddField(
            model_name='all_details',
            name='email1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reglog.registration'),
        ),
    ]
